F = fopen("a.bin","r");
A = fread(F,Inf,"double");
fclose(F);
side = sqrt(length(A));
A = reshape(A,[side,side]);
F = fopen("a.bin","w");
lambda = sort(eig(A));
a = 2/(lambda(1) + lambda(end));
fwrite(F,a,"double");
fclose(F);
